# Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# POST rooms
POST {{baseUrl}}/rooms
content-type: application/json

{
  "name": "Sala de teste",
  "description": "Descrição da sala de teste"
}

###

# GET room questions

@roomId = {{getRooms.response.body.$[1].id}}

GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# POST questions
POST {{baseUrl}}/rooms/7feaea24-f78e-473b-9474-e73b54e59cab/questions
content-type: application/json

{
  "question": "O que é vue.js e sua diferença em relação ao Angular?"
}
